# ============================================================================
# Auto-generated by "Unreal Render — CVar Manager"
# Movie Render Graph → "Execute Script" node (Script Class = RenderCVarOverrides_MyHeroShot)
# Applies render CVars on job start and restores the editor's values on finish.
# Preset: My Hero Shot
# Target engine: UE 5.7.4
# ============================================================================
import unreal

# Runtime / render-graph CVars — applied live at job start, restored at job finish.
RENDER_CVARS = {
    "r.Lumen.HardwareRayTracing": "1",  # Use GPU RT cores for Lumen tracing instead of SDF.
    "r.Lumen.HardwareRayTracing.LightingMode": "2",  # 0 = surface-cache lighting; 2 = hit-lighting (evaluate real material at hit).
    "r.Lumen.ScreenProbeGather.DownsampleFactor": "8",  # Spacing of final-gather screen probes (lower = denser).
    "r.Lumen.ScreenProbeGather.RadianceCache.ProbeResolution": "64",  # Resolution of each radiance-cache probe.
    "r.Lumen.ScreenProbeGather.RadianceCache.NumProbesToTraceBudget": "250",  # How many radiance-cache probes update per frame.
    "r.Lumen.ScreenProbeGather.MaxRayIntensity": "20",  # Clamps the brightness a single GI ray can contribute.
    "r.LumenScene.SurfaceCache.CardMaxResolution": "1024",  # Max texel resolution of surface-cache cards.
    "r.Lumen.Reflections.DownsampleFactor": "1",  # Reflection trace resolution (1 = full).
    "r.Lumen.Reflections.MaxRoughnessToTrace": "1",  # Roughest surface that still gets traced reflections (-1 = auto).
    "r.Lumen.ScreenProbeGather.Temporal.MaxFramesAccumulated": "8",  # Frames of GI temporal accumulation.
    "r.LumenScene.Lighting.ForceLightingUpdate": "0",  # Force a full Lumen scene lighting update every frame.
    "r.Nanite": "1",  # Master switch for Nanite virtualized geometry.
    "r.Nanite.MaxPixelsPerEdge": "1",  # Target triangle size in pixels (1 = full detail).
    "r.Nanite.Streaming.StreamingPoolSize": "2688",  # VRAM (MB) reserved for streaming Nanite clusters.
    "r.Nanite.Streaming.MaxPageInstallsPerFrame": "2048",  # How many geometry pages can be made resident per frame.
    "r.Nanite.Streaming.MaxPendingPages": "1024",  # Size of the page request queue.
    "r.Nanite.Streaming.NumInitialRootPages": "4096",  # Root pages kept resident up-front.
    "r.Nanite.AllowSkinnedMeshes": "1",  # Allow skinned (animated) meshes to use Nanite.
    "r.Shadow.Virtual.MaxPhysicalPages": "12288",  # Size of the VSM physical page pool.
    "r.Shadow.Virtual.Cache": "1",  # Cache shadow pages across frames.
    "r.Shadow.Virtual.ResolutionLodBiasDirectional": "-2",  # Resolution bias for sun/moon shadows (more negative = sharper).
    "r.Shadow.Virtual.ResolutionLodBiasLocal": "-0.5",  # Resolution bias for local-light shadows.
    "r.Shadow.Virtual.SMRT.RayCountDirectional": "16",  # Rays per pixel for soft directional shadows.
    "r.Shadow.Virtual.SMRT.RayCountLocal": "16",  # Rays per pixel for soft local-light shadows.
    "r.Shadow.Virtual.SMRT.SamplesPerRayDirectional": "8",  # Samples taken along each directional shadow ray.
    "r.Shadow.Virtual.SMRT.SamplesPerRayLocal": "8",  # Samples taken along each local shadow ray.
    "r.Shadow.Virtual.Clipmap.FirstLevel": "7",  # Finest directional clipmap level.
    "r.Shadow.Virtual.Clipmap.LastLevel": "23",  # Coarsest clipmap level / max shadow distance.
    "r.SkyAtmosphere": "1",  # Physically-based sky + aerial perspective.
    "r.SkyAtmosphere.FastSkyLUT": "0",  # Use a cheap LUT for the sky instead of per-pixel.
    "r.SkyAtmosphere.SampleCountMax": "224",  # Max raymarch samples through the atmosphere.
    "r.SkyAtmosphere.AerialPerspectiveLUT.SampleCountMaxPerSlice": "8",  # Samples per aerial-perspective depth slice.
    "r.SkyAtmosphere.AerialPerspectiveLUT.DepthResolution": "32",  # Depth slices for aerial perspective.
    "r.SkyAtmosphere.MultiScatteringLUT.HighQuality": "1",  # Higher-quality multiple-scattering LUT.
    "r.VolumetricFog": "1",  # Froxel volumetric fog & light shafts.
    "r.VolumetricFog.GridPixelSize": "4.6",  # Screen-space froxel size in pixels (lower = sharper).
    "r.VolumetricFog.GridSizeZ": "256",  # Number of depth slices in the fog volume.
    "r.VolumetricFog.TemporalReprojection": "1",  # Reuse previous-frame fog to denoise.
    "r.VolumetricFog.HistoryWeight": "0.9",  # How strongly previous fog frames are blended.
    "r.AOGlobalDistanceField": "1",  # Build the merged global distance field.
    "r.AmbientOcclusionLevels": "3",  # Number of SSAO mip levels (-1 = auto).
    "r.AmbientOcclusion.Method": "1",  # 0 = SSAO, 1 = GTAO (ground-truth).
    "r.GTAO.NumAngles": "4",  # Directions sampled by GTAO.
    "r.SkinCache.Mode": "1",  # GPU skin cache mode.
    "r.SkinCache.RecomputeTangents": "2",  # Recompute tangents after skinning (2 = all).
    "r.SeparateTranslucency": "1",  # Render translucency in a separate pass so DOF/upscale handle it correctly.
    "r.SeparateTranslucencyScreenPercentage": "100",  # Resolution % of the separate-translucency buffer.
    "r.TranslucencyLightingVolume": "1",  # Froxel volume that lights translucent surfaces & particles.
    "r.TranslucentSortPolicy": "0",  # Sorting basis for translucent draws (0 = by projected distance).
    "r.Lumen.TranslucencyVolume.Enable": "1",  # Lumen GI injected into the translucency lighting volume.
    "r.SubsurfaceScattering": "1",  # Screen-space subsurface scattering (skin, wax, foliage).
    "r.SSS.Quality": "1",  # SSS sampling quality (1 = high/adaptive).
    "r.SSS.Scale": "1",  # Global multiplier on SSS radius.
    "r.SSS.HalfRes": "0",  # Run SSS at half resolution.
    "r.BloomQuality": "5",  # Bloom convolution quality (0 off…5 best).
    "r.DepthOfFieldQuality": "2",  # Cinematic depth-of-field quality (0 off…2).
    "r.LensFlareQuality": "0",  # Bokeh lens-flare quality (0 off…3).
    "r.AntiAliasingMethod": "4",  # AA method (0 none,1 FXAA,2 TAA,4 TSR).
    "r.TSR.History.SampleCount": "16",  # TSR temporal history depth.
    "r.ScreenPercentage": "100",  # Primary render resolution % of output.
    "r.MotionBlurQuality": "4",  # Motion-blur quality (0 off…4).
    "r.Streaming.PoolSize": "5888",  # VRAM (MB) budget for streamed textures.
    "r.Streaming.LimitPoolSizeToVRAM": "1",  # Clamp pool to physical VRAM.
    "r.Streaming.FullyLoadUsedTextures": "1",  # Load full-res mips for all visible textures.
    "r.MipMapLODBias": "0",  # Global mip LOD bias.
    "r.GBufferFormat": "1",  # GBuffer precision (1 = high).
    "MovieRenderPipeline.NumWarmUpFramesWithTemporalSampling": "48",  # Frames rendered (discarded) before capture to converge temporal systems.
    "r.MyCustom.Foo": "42",  # Not found in the 5.7.4 dump — check spelling.
}

# ----------------------------------------------------------------------------
# PROJECT settings below are read at engine startup and CANNOT be changed at
# render time. Set them in Project Settings / DefaultEngine.ini (then restart):
#     r.DynamicGlobalIlluminationMethod = 1
#     r.ReflectionMethod = 1
#     r.RayTracing = 1
#     r.RayTracing.Shadows = 1
#     r.DistanceFields = 1
#     r.DefaultFeature.AutoExposure = 0
# ----------------------------------------------------------------------------

@unreal.uclass()
class RenderCVarOverrides_MyHeroShot(unreal.MovieGraphScriptBase):
    """Enforce render CVars for this job, then cleanly restore the editor."""

    def _post_init(self):
        self._originals = {}

    def _world(self):
        return unreal.EditorLevelLibrary.get_editor_world()

    @unreal.ufunction(override=True)
    def on_job_start(self, in_job_copy):
        super().on_job_start(in_job_copy)
        world = self._world()
        self._originals = {}
        unreal.log("[RenderCVars] Applying %d CVars" % len(RENDER_CVARS))
        for name, value in RENDER_CVARS.items():
            try:
                self._originals[name] = unreal.SystemLibrary.get_console_variable_string_value(name)
            except Exception:
                self._originals[name] = None
            unreal.SystemLibrary.execute_console_command(world, "%s %s" % (name, value))
        unreal.log_warning("[RenderCVars] %d CVars enforced for render" % len(RENDER_CVARS))

    @unreal.ufunction(override=True)
    def on_job_finished(self, in_job_copy, in_output_data):
        super().on_job_finished(in_job_copy, in_output_data)
        world = self._world()
        restored = 0
        for name, value in self._originals.items():
            if value is not None and value != "":
                unreal.SystemLibrary.execute_console_command(world, "%s %s" % (name, value))
                restored += 1
        unreal.log("[RenderCVars] Restored %d editor CVars" % restored)
